version: "3.4"

services:

  flux-psij:
    image: exaworks/flux-psij
    container_name: flux-psij
    hostname: flux-psij
    build:
      context: ..
      dockerfile: ./docker/flux-psij.dockerfile
    environment:
      - FLUX_CONF_DIR=/etc/flux/system
    networks:
      - flux-network
    volumes:
      - flux-system:/etc/flux/system/
      - flux-workdir:/home/fluxuser/workdir/
    command: /bin/bash
    tty: true

  flux-sched:
    image: fluxrm/flux-sched:latest
    container_name: flux-sched
    hostname: flux-sched
    environment:
      - FLUX_CONF_DIR=/etc/flux/system
    networks:
      - flux-network
    volumes:
      - flux-system:/etc/flux/system/
      - flux-workdir:/home/fluxuser/workdir/
    command: /bin/bash -c "flux broker"
    tty: true

networks:
  flux-network:
    name: flux-network

volumes:
  flux-system:
    name: flux-system
  flux-workdir:
    name: flux-workdir
